spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: user
    password: P@ssw0rd1
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  # Disable Kafka auto-configuration to avoid connection attempts
  auto-configure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

market-data-srvc:
  url: http://localhost:8082