spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?currentSchema=portfolio&sslmode=require&channel_binding=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  flyway:
    enabled: true
    default-schema: portfolio
    create-schemas: false
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    # JPA specific properties (how spring interacts with database)
    hibernate:
      ddl-auto: validate  # Validate that entities match the DB
      # ddl-auto: update  # Automatically create/update tables based on entities

    # Hibernate specific implementation properties (direct to hibernate)
    properties:
      hibernate:
        default_schema: portfolio
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Use PostgreSQL dialect
      format_sql: true

    # Show SQL statements in the console. Set to false in production.
    show-sql: true

  kafka:
    bootstrap-servers: apex-kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8080

market-data-srvc:
  url: http://market-data-srvc:8080
